import * as crypto from 'crypto';

export type DispatchStatus =
  | 'pending_approval'
  | 'rejected'
  | 'running'
  | 'completed'
  | 'error'
  | 'cancelled';

export interface DispatchRecord {
  /** RPC id — the key peers use to poll this record. Generated by the receiver. */
  rpcId: string;
  /** WindowId of the peer that initiated the dispatch. */
  fromWindowId: string;
  /** Task prompt sent to the agent. */
  task: string;
  /** Short label for display. */
  label: string;
  /** Local agent id once spawned. Absent until approval. */
  agentId?: string;
  status: DispatchStatus;
  /** Free-form reason for rejection / error. */
  reason?: string;
  result?: string;
  error?: string;
  cost?: { totalTokens: number; totalCost: number };
  createdAt: number;
  completedAt?: number;
}

/**
 * In-memory map of dispatch requests received by this window.
 * Keyed by rpcId. Records are retained for 10 minutes after completion so
 * the sender has time to poll.
 */
export class DispatchRegistry {
  private records = new Map<string, DispatchRecord>();
  private readonly retentionMs = 10 * 60 * 1000;
  private cleanupTimer?: NodeJS.Timeout;

  constructor() {
    this.cleanupTimer = setInterval(() => this.cleanup(), 60_000);
    // Don't block process exit.
    this.cleanupTimer.unref?.();
  }

  dispose(): void {
    if (this.cleanupTimer) clearInterval(this.cleanupTimer);
  }

  create(input: { fromWindowId: string; task: string; label: string }): DispatchRecord {
    const rec: DispatchRecord = {
      rpcId: crypto.randomUUID(),
      fromWindowId: input.fromWindowId,
      task: input.task,
      label: input.label,
      status: 'pending_approval',
      createdAt: Date.now(),
    };
    this.records.set(rec.rpcId, rec);
    return rec;
  }

  get(rpcId: string): DispatchRecord | undefined {
    return this.records.get(rpcId);
  }

  findByAgentId(agentId: string): DispatchRecord | undefined {
    for (const rec of this.records.values()) {
      if (rec.agentId === agentId) return rec;
    }
    return undefined;
  }

  update(rpcId: string, patch: Partial<DispatchRecord>): DispatchRecord | undefined {
    const rec = this.records.get(rpcId);
    if (!rec) return undefined;
    Object.assign(rec, patch);
    return rec;
  }

  private cleanup(): void {
    const cutoff = Date.now() - this.retentionMs;
    for (const [rpcId, rec] of this.records) {
      const terminal =
        rec.status === 'completed' || rec.status === 'error' ||
        rec.status === 'cancelled' || rec.status === 'rejected';
      if (terminal && rec.completedAt && rec.completedAt < cutoff) {
        this.records.delete(rpcId);
      }
    }
  }
}
